name: generate-changelog
description: ""

inputs:
  git-cliff-args:
    description: ""
    required: false
    default: --current
  git-cliff-config:
    description: ""
    required: false
    default: ${GITHUB_ACTION_PATH}/../cliff.toml
  trim-version-and-date:
    description: ""
    required: false
    default: "true"
outputs:
  changelog:
    description: ""
    value: ${{ steps.generate-changelog.outputs.changelog }}

runs:
  using: composite
  steps:
    - name: Set up git-cliff
      uses: kenji-miyake/setup-git-cliff@v1

    - name: Generate changelog
      id: generate-changelog
      shell: bash
      run: |
        # Generate changelog
        git cliff --config ${{ inputs.git-cliff-config }} \
          -vv --strip header ${{ inputs.git-cliff-args }} --context --output context.json


